# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
#           filename: metrics.svg
          base: header, activity
#           header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_introduction_title: no # Hide section title
#           plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored:
#           plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, python, ejs
          plugin_languages_skipped: lowlighter
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used
#           plugin_languages_sections: most-used, recently-used          
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
#           plugin_topics: yes
#           plugin_topics_limit: 0
#           plugin_topics_mode: mastered
#           plugin_notable: yes
#           plugin_notable_repositories: yes
#           plugin_discussions: yes
#           config_order: base.header, isocalendar, languages, notable, discussions, topics
